### ISSUE TITLE
Component tracker

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk-components#18]
This is a central progress/tracking issue for components based on @tijmenb's list (#3)

## Components

* [x] Accordion (too complex, maybe out of scope) #45 
* [x] Back link #13 
* [x] Breadcrumbs #12 
* [x] Details #25 
* [x] Footer #35 
* [x] Header #17 
* [x] Inset text #9 
* [x] Panel 8ca545128c
* [x] Phase banner #8 
* [x] Start now button #1 
* [x] Summary list #48 
* [ ] Table (too complex, maybe out of scope)
* [x] Tabs (maybe too complex initially, probably relies on the enhanced content block functionality of View Component) #42 
* [x] Tag #4 
* [x] Warning text #28 

## Helpers

* [x] `#govuk_link_to` #15 
* [x] `#govuk_mail_to` #36 
* [x] `#govuk_button_to` (thinking this should map to Rails' `button_to` but maybe there's also need for a link styled as a button #36 
* [x] `#govuk_back_to_top_link` #19 
* [x] Skip link #20 

## Other useful stuff

Perhaps this shouldn't be in here, but it's something that's _probably_ useful to every project. Maybe it's better suited to the DfE Rails Boilerplate

* [x] ~~A GOV.UK date format that can be used by Rails' date helpers, eg `object.submitted_on.to_formatted_s(:govuk)`, see [example](https://github.com/DFE-Digital/schools-experience/blob/master/config/initializers/date_format.rb#L3).~~ A PR with this functionality has been [submitted to the boilerplate](DFE-Digital/govuk-rails-boilerplate/pull/272)

**Comment by rjlynch** [comment]
I think we should include a back_to_top link helper. I saw that pulled out into a helper and used a bunch on SE

**Comment by aliuk2012** [comment]
I think this list should be in the Readme so its more visible which components it does have.

**Comment by peteryates** [comment]
Everything except Table is in. Closing this as table might be a bit _involved_, opened #53 to address it.
