### ISSUE TITLE
Add navigation support to the footer

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk-components#247]
While documenting the library (#244) I noticed that the footer doesn't currently allow navigation options to be passed in.

Footer navigation looks like this:

![Screenshot-2021-09-05-16:26:26](https://user-images.githubusercontent.com/128088/132132240-874e8518-539b-4561-af00-954bf7d8e404.png)

This appears to have been an oversight and should really be supported.

## Suggested approach

Add a slot called `NavigationSection` that can be rendered multiple times.

Each section renders items; these could be a set of `NavigationItem` components (first section) or we can add a `#govuk_footer_link_to` link helper (second section).

```ruby
govuk_footer do |footer|
  # via a subcomponent
  footer.navigation_section(title: "Departments and policy", columns: 1) do |navigation_section|
    navigation_section.item(text: "How government works", href: "/how-government-works")
    navigation_section.item(text: "Departments", href: "/departments")
  end

  # using a link helper
  footer.navigation_section(title: "Second section", columns: 2, items: [
    govuk_footer_link_to("Worldwide", href: "/worldwide"),
    govuk_footer_link_to("Policies", href: "/policies")
  ])
end
```

I prefer the array of links approach ☝🏽 

## Tasks

* [ ] Add a `NavigationSection` component for the footer
* [ ] Write some tests covering behaviour
* [ ] Update the component previews and docs

**Comment by paulrobertlloyd** [comment]
Should this not mirror the approach used for the header (aka the first option)? Also, the second option could result in links with the wrong class applied.

**Comment by peteryates** [comment]
Yeah, I guess that makes sense. The subcomponent will essentially mimic the behaviour of `link_to` but with a custom class, which is why a custom helper seems like a good fit. [Breadcrumbs](https://github.com/DFE-Digital/govuk-components/pull/244/commits/fd08049c687433dbac69e850fca4f570a0b305fe#diff-3b6040258b7fd06c5c58aba043bb54a7b0b7d92d17c36a1b331d717d20ff6f9fR32) can work in that fashion too.

**Comment by peteryates** [comment]
This was fixed somewhere along the way.
